In [1]:
import torch
t1 = torch.zeros(2, 4)
t1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [88]:
t2 = torch.tensor([[1, 2], [3, 4]])
t2

tensor([[1, 2],
        [3, 4]])

In [21]:
t3=torch.ones(2,6)
t3

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [54]:
t4 = torch.randn(2, 3)
t4

tensor([[-0.9715, -2.0231, -1.8942],
        [-1.4120, -0.0294, -0.8347]])

In [83]:
t5 = torch.arange(0, 20, 2)
t5

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [87]:
t5

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [86]:
t6=t5[::5]
print(t6)
t6.reshape(1,2)

tensor([ 0, 10])


tensor([[ 0, 10]])

In [89]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

In [90]:
e = torch.matmul(a, b)
e

tensor([[19, 22],
        [43, 50]])

In [97]:
tensor1 = torch.randn(10, 3, 4)
tensor1


tensor([[[ 0.5970,  1.0391, -1.2655,  2.7095],
         [ 0.2186, -1.0732, -0.3047, -1.4860],
         [ 1.0611, -0.1703, -0.5001,  1.7283]],

        [[-1.1145,  0.9305, -0.5409, -1.5022],
         [ 1.0807,  0.2475, -0.5903,  0.0677],
         [ 0.9032,  0.6509, -1.1615, -0.1847]],

        [[ 0.9585,  0.9891, -0.0229,  0.7727],
         [ 0.1765,  0.9412, -0.6655, -0.7620],
         [-0.2278,  0.2078, -1.8165,  0.0659]],

        [[-0.0754,  1.1038, -0.6374, -1.3876],
         [ 0.2398,  0.0245, -2.0449, -0.4228],
         [-0.5098, -1.0832, -1.7381,  0.4565]],

        [[ 0.1373,  0.0728, -0.5635, -0.5003],
         [ 0.6463,  0.3351, -0.9926,  0.3342],
         [-1.1079, -1.2175, -0.3686,  0.1664]],

        [[-0.4963,  1.5160,  0.7579, -0.0753],
         [-2.3415,  0.0544, -1.5581, -0.9984],
         [-0.5209,  1.8427,  1.7606,  1.1177]],

        [[ 0.1515,  0.6056, -0.4098, -0.7394],
         [ 1.5952,  0.0905, -1.0733, -0.7483],
         [ 0.6534, -0.3864,  1.9645,  0.3405]],


In [ ]:
tensor2 = torch.randn(4)
tensor2.shape

torch.Size([4])

: 

In [60]:
torch.reshape(t4, (-1,))

tensor([-0.9715, -2.0231, -1.8942, -1.4120, -0.0294, -0.8347])

In [67]:
t4.view(-1,2)

tensor([[-0.9715, -2.0231],
        [-1.8942, -1.4120],
        [-0.0294, -0.8347]])

In [33]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor = torch.tensor([1, 2, 3]).to(device)
tensor.size()

torch.Size([3])

In [2]:
class Car :
    def __init__(self, color, speed):
        self.color = color
        self.speed = speed
car = Car('red','100mph')
car.speed

'100mph'

In [3]:
class Car():
    def drive(self):
        print('vroom')
class Audi(Car):
    pass
audi = Audi()
audi.drive()

vroom


In [3]:
import torch
a = torch.tensor([1, 2, 3])         # (3,)
b = torch.tensor([[1], [2], [3]])   # (3, 1)
c = a + b   
c

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [7]:
# Создание тензора размером (3, 4) со случайными числами
t = torch.randn(3, 4)

# Поэлементное и матричное умножение
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
elementwise = a * b
matrix_mult = torch.matmul(a, b)
print(elementwise)
print(matrix_mult)

tensor([[ 5, 12],
        [21, 32]])
tensor([[19, 22],
        [43, 50]])


In [11]:
import torch.nn as nn
x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[2.0], [4.0], [6.0]])

# Модель
model = nn.Linear(1, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
loss_fn = nn.MSELoss()

# Обучение
for epoch in range(100):
    predictions = model(x)
    loss = loss_fn(predictions, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
x = torch.tensor([[1.0], [2.0], [4.0]])
predict = model(x)
predict

tensor([[1.9313],
        [3.9852],
        [8.0932]], grad_fn=<AddmmBackward0>)

In [19]:
t = torch.tensor([[1, 2], [3, 4]])
print(t.size())
reshaped = t.view(4)  # Изменение размера
print(reshaped)
squeezed = t.unsqueeze(0)  # Добавление размерности
print(squeezed.size())
permuted = t.T
print(permuted)

torch.Size([2, 2])
tensor([1, 2, 3, 4])
torch.Size([1, 2, 2])
tensor([[1, 3],
        [2, 4]])


In [3]:
import torch
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])
sum = a + b
dot_product = torch.dot(a, b)
print(dot_product)
print(a*b)
matrix_product = torch.matmul(a.unsqueeze(0), b.unsqueeze(1))
print(a.unsqueeze(0), b.unsqueeze(1))
print(matrix_product)

tensor(11)
tensor([3, 8])
tensor([[1, 2]]) tensor([[3],
        [4]])
tensor([[11]])


In [27]:
import numpy as np
X = np.random.rand(100, 1)
y = 3 * X.squeeze()


array([[0.88167517],
       [0.84106045],
       [0.30264685],
       [0.38269427],
       [0.80218794],
       [0.2628552 ],
       [0.14056653],
       [0.33957726],
       [0.6216242 ],
       [0.34706247],
       [0.78013535],
       [0.41216062],
       [0.63535129],
       [0.2457001 ],
       [0.11567756],
       [0.64219674],
       [0.72122381],
       [0.5481129 ],
       [0.73485736],
       [0.47803096],
       [0.89370837],
       [0.1796335 ],
       [0.57764983],
       [0.93470297],
       [0.14111943],
       [0.15394754],
       [0.16716709],
       [0.13301006],
       [0.02831033],
       [0.5741126 ],
       [0.95770027],
       [0.18857408],
       [0.60338903],
       [0.21581921],
       [0.42649772],
       [0.35721014],
       [0.74116207],
       [0.87755403],
       [0.9221051 ],
       [0.51813807],
       [0.58272626],
       [0.86345427],
       [0.73501504],
       [0.24671819],
       [0.97368781],
       [0.62049207],
       [0.88515621],
       [0.911